#!/usr/bin/env python3
"""Render a TrueType font to an anti-aliased greyscale atlas as C source.

The kernel has no floating point, no maths library and no font parser, so
glyphs are rasterised here, at build time, and embedded as plain bytes. Each
byte is a coverage value: 0 where the glyph does not cover the pixel, 255
where it fully covers it, and something between at the edges. Blending that
coverage against the background at runtime is what produces smooth edges,
and it costs one multiply per pixel rather than a rasteriser in the kernel.

Producing this at build time also keeps the font itself out of the repository
as a binary blob -- it comes from the toolchain image.
"""

import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126          # printable ASCII


def render(font_path, size):
    font = ImageFont.truetype(font_path, size)

    # Measure every glyph first: the cell has to fit the tallest ascender and
    # the deepest descender, or characters clip into their neighbours.
    widths, tops, bottoms = [], [], []
    for code in range(FIRST, LAST + 1):
        box = font.getbbox(chr(code))
        widths.append(font.getlength(chr(code)))
        tops.append(box[1])
        bottoms.append(box[3])

    cell_w = int(max(widths) + 0.999)
    top    = min(tops)
    cell_h = max(bottoms) - top

    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cell_w, cell_h), 0)
        ImageDraw.Draw(img).text((0, -top), chr(code), font=font, fill=255)
        glyphs.append(list(img.getdata()))

    return cell_w, cell_h, glyphs


def emit(name, cell_w, cell_h, glyphs, out):
    out.write(f"/* {name}: {cell_w}x{cell_h} cells, ASCII {FIRST}-{LAST}.\n")
    out.write(" * Generated by tools/genfont.py -- do not edit by hand.\n */\n")
    out.write(f"const unsigned char {name}[{len(glyphs)}][{cell_w * cell_h}] = {{\n")

    for code, data in enumerate(glyphs, start=FIRST):
        ch = chr(code) if code != 92 else "backslash"
        out.write(f"    {{ /* '{ch}' */\n")
        for row in range(cell_h):
            vals = data[row * cell_w:(row + 1) * cell_w]
            out.write("        " + ",".join(f"{v:3d}" for v in vals) + ",\n")
        out.write("    },\n")

    out.write("};\n\n")


def main():
    font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    ui_path   = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

    with open(sys.argv[1], "w") as out:
        out.write("/* Anti-aliased font atlases, generated at build time.\n")
        out.write(" * See tools/genfont.py. */\n\n")

        for name, path, size in (
            ("font_mono", font_path, 15),
            ("font_ui",   ui_path,   15),
        ):
            w, h, glyphs = render(path, size)
            emit(name, w, h, glyphs, out)
            out.write(f"const int {name}_w = {w};\n")
            out.write(f"const int {name}_h = {h};\n\n")
            print(f"{name}: {w}x{h}", file=sys.stderr)


if __name__ == "__main__":
    main()
