#!/usr/bin/env python3
"""Render TrueType fonts to anti-aliased greyscale atlases as C source.

The kernel has no floating point, no maths library and no font parser, so
glyphs are rasterised here, at build time, and embedded as plain bytes. Each
byte is a coverage value: 0 where the glyph does not cover the pixel, 255
where it fully covers it, and values between at the edges. Blending that
coverage against the background is what gives smooth edges, and it costs one
multiply per pixel rather than a rasteriser in the kernel.

Advance widths are emitted alongside the bitmaps. Without them a proportional
face has to be drawn on a fixed grid, which spaces every glyph as though it
were as wide as the widest one -- an 'i' taking the same room as a 'W'. That
looks worse than a bitmap font, not better.
"""

import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126


def render(font_path, size):
    font = ImageFont.truetype(font_path, size)

    rights, tops, bottoms, advances = [], [], [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        box = font.getbbox(ch)
        rights.append(box[2])
        tops.append(box[1])
        bottoms.append(box[3])
        advances.append(int(round(font.getlength(ch))))

    cell_w = max(max(rights), max(advances)) + 1
    top = min(tops)
    cell_h = max(bottoms) - top

    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cell_w, cell_h), 0)
        ImageDraw.Draw(img).text((0, -top), chr(code), font=font, fill=255)
        glyphs.append(list(img.getdata()))

    return cell_w, cell_h, glyphs, advances


def emit(name, cell_w, cell_h, glyphs, advances, out):
    out.write("/* " + name + ": " + str(cell_w) + "x" + str(cell_h) + " cells,")
    out.write(" ASCII 32-126. Generated by tools/genfont.py. */\n")
    out.write("const unsigned char " + name + "[95][" + str(cell_w * cell_h) + "] = {\n")

    for data in glyphs:
        out.write("    {\n")
        for row in range(cell_h):
            vals = data[row * cell_w:(row + 1) * cell_w]
            out.write("        " + ",".join(str(v) for v in vals) + ",\n")
        out.write("    },\n")

    out.write("};\n\n")

    out.write("/* How far to move right after each glyph. Not the same as the\n")
    out.write(" * cell width for a proportional face. */\n")
    out.write("const unsigned char " + name + "_adv[95] = {\n    ")
    out.write(", ".join(str(a) for a in advances))
    out.write("\n};\n\n")

    out.write("const int " + name + "_w = " + str(cell_w) + ";\n")
    out.write("const int " + name + "_h = " + str(cell_h) + ";\n\n")


def main():
    fonts = (
        ("font_mono", "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 15),
        ("font_ui", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 15),
    )

    with open(sys.argv[1], "w") as out:
        out.write("/* Anti-aliased font atlases, generated at build time.\n")
        out.write(" * See tools/genfont.py. */\n\n")

        for name, path, size in fonts:
            w, h, glyphs, adv = render(path, size)
            emit(name, w, h, glyphs, adv, out)
            sys.stderr.write(name + ": " + str(w) + "x" + str(h) +
                             " advances " + str(min(adv)) + "-" + str(max(adv)) + "\n")


if __name__ == "__main__":
    main()
