#!/usr/bin/env python3
"""Convert an image into a palettised C array the kernel can draw.

The kernel has no image decoder. Adding one means a PNG or JPEG implementation
-- inflate, or a DCT and Huffman tables -- inside a freestanding binary with no
libc, which is a project rather than a feature and teaches nothing about
operating systems. The decoding therefore happens here, at build time, and what
the kernel receives is the thing every framebuffer ultimately wants anyway: an
array of pixels.

The output is palettised because a wallpaper is mostly a few colours used
repeatedly. Storing 24-bit pixels for a half-resolution 1920x1080 image costs
1.5 MB in the kernel image; a 256-entry palette with one byte per pixel costs
518 KB and, for artwork rather than a photograph, is visually identical. That
is the same trade every 8-bit display mode made, for the same reason.

The image is stored at half the screen dimensions and doubled when drawn. A
wallpaper sits behind everything and is never examined closely, and half
resolution halves both the kernel size and the memory traffic of drawing it.

Usage:
    genwallpaper.py <image> [output.c] [width] [height]
"""

import sys
from PIL import Image

DEFAULT_W, DEFAULT_H = 960, 540


def cover_fit(img, w, h):
    """Scale to fill w x h, cropping whatever overflows.

    Letterboxing would leave bars, and stretching would distort; filling and
    cropping is what a desktop does with a wallpaper whose aspect ratio does
    not match the screen.
    """
    src_w, src_h = img.size

    if src_w * h > w * src_h:
        # Source is wider: match the height and crop the sides.
        new_h = h
        new_w = max(w, round(src_w * h / src_h))
    else:
        new_w = w
        new_h = max(h, round(src_h * w / src_w))

    img = img.resize((new_w, new_h), Image.LANCZOS)

    left = (new_w - w) // 2
    top = (new_h - h) // 2

    return img.crop((left, top, left + w, top + h))


def emit(img, out_path, name="wallpaper_image"):
    w, h = img.size

    # Quantise to 256 colours. The palette is chosen from the image itself, so
    # a picture using few colours loses nothing at all.
    quant = img.convert("RGB").quantize(colors=256, method=Image.MEDIANCUT)

    palette = quant.getpalette()[: 256 * 3]
    pixels = quant.tobytes()

    assert len(pixels) == w * h, "unexpected pixel count"

    with open(out_path, "w", newline="\n") as f:
        f.write("/* Generated by tools/genwallpaper.py -- do not edit.\n"
                " *\n"
                " * A palettised image, decoded at build time because the kernel has no\n"
                " * image decoder and should not grow one. Stored at half the screen\n"
                " * dimensions and doubled when drawn.\n"
                " */\n")
        f.write('#include "wallpaper_image.h"\n\n')

        f.write("const int wallpaper_image_w = %d;\n" % w)
        f.write("const int wallpaper_image_h = %d;\n\n" % h)

        f.write("/* 256 entries of red, green, blue. */\n")
        f.write("const uint8_t wallpaper_image_palette[256 * 3] = {\n")
        for i in range(0, 256 * 3, 12):
            row = ", ".join("%3d" % v for v in palette[i:i + 12])
            f.write("    %s,\n" % row)
        f.write("};\n\n")

        f.write("/* One palette index per pixel, left to right, top to bottom. */\n")
        f.write("const uint8_t wallpaper_image_pixels[%d] = {\n" % (w * h))
        for i in range(0, len(pixels), 24):
            row = ",".join("%d" % b for b in pixels[i:i + 24])
            f.write("%s,\n" % row)
        f.write("};\n")

    return w, h


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1

    src = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "kernel/wallpaper_image.c"
    w = int(sys.argv[3]) if len(sys.argv) > 3 else DEFAULT_W
    h = int(sys.argv[4]) if len(sys.argv) > 4 else DEFAULT_H

    img = Image.open(src)
    print("source     : %s  %dx%d  %s" % (src, img.size[0], img.size[1], img.mode))

    img = cover_fit(img, w, h)
    ow, oh = emit(img, out)

    print("written    : %s  %dx%d" % (out, ow, oh))
    print("kernel cost: %d bytes of pixels + 768 of palette" % (ow * oh))
    return 0


if __name__ == "__main__":
    sys.exit(main())
